---
title: How to nail presentation?
subtitle: "`umich-quarto-reveal` will help you nail it!"
format: clean-revealjs
author:
  - name: Jozef Rivest
    orcid: 0000-0000-0000-0000
    email: "jrivest@umich.edu"
    affiliations: "Department of Political Science, University of Michigan"
date: last-modified
---

## Example slide

### This is a subtitle

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

## Quarto is Great to Present your R Plot!

### This is a cool graph

```{r}
library(palmerpenguins)
library(tidyverse)

dat <- penguins

ggplot(
  dat,
  aes(x = flipper_length_mm, y = body_mass_g, color = species, shape = species)
) +
  geom_point() +
  geom_smooth(method = lm) +
  theme_bw()
```

## Additional theme classes

### Some extra things you can do with the clean theme

Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

## Want to use it?

```bash
quarto use template JozefRivest/umich-quarto-reveal
```

And start your presentation with `template.qmd`! 
